#!/bin/bash

PYKUBE=
for pykube in $ /root/hroot/htools/pykube ~/work/htools/pykube /root/htools/pykube
do
    if test -e "$pykube";then
        PYKUBE=$pykube
        break
    fi
done


_k_do() {
    $PYKUBE "$@"
}
_k_scale() {
    local kind="$1"
    local object="$2"
    local num="${3:-0}"
    shift
    shift
    shift
    _k_do scale "$kind" "$object" --replicas="$num" "$@"
}

_k_recreate_file() {
    kubectl delete -f "$@"
    echo ============
    kubectl create -f "$@"
}


if test -n "$PYKUBE";then

## get 
alias kg="_k_do get"
alias kgp="_k_do get pod"
alias kgs="_k_do get svc"
alias kgd="_k_do get deployment"
alias kgn="_k_do get node"
alias kgi="_k_do get ingress"
alias kgr="_k_do get release"
alias kgc="_k_do get configmap"
alias kgna="_k_do get net-attach-def"
alias kgnw="_k_do get net"
alias kga="_k_do get all"

## get as yaml
alias ky="_k_do yaml"
alias kyp="_k_do yaml pod"
alias kys="_k_do yaml svc"
alias kyd="_k_do yaml deployment"
alias kyn="_k_do yaml node"
alias kyi="_k_do yaml ingress"
alias kyr="_k_do yaml release"
alias kyc="_k_do yaml configmap"
alias kyna="_k_do yaml net-attach-def"
alias kynw="_k_do yaml net"
alias kya="_k_do yaml all"

## describe
alias kd="_k_do describe"
alias kdp="_k_do describe pod"
alias kds="_k_do describe svc"
alias kdd="_k_do describe deployment"
alias kdn="_k_do describe node"
alias kdi="_k_do describe ingress"
alias kdr="_k_do describe release"
alias kdc="_k_do describe configmap"
alias kdna="_k_do describe net-attach-def"
alias kdnw="_k_do describe net"
alias kda="_k_do describe all"

## delete
alias kdd-="_k_do delete"
alias kddp="_k_do delete pod"
alias kdds="_k_do delete svc"
alias kddd="_k_do delete deployment"
alias kddi="_k_do delete ingress"
alias kddr="_k_do delete release"
alias kddc="_k_do delete configmap"
alias kddna="_k_do delete net-attach-def"
alias kddnw="_k_do delete net"
alias kdda="_k_do delete all"

## edit
alias ke="_k_do edit"
alias kep="_k_do edit pod"
alias kes="_k_do edit svc"
alias ked="_k_do edit deployment"
alias kei="_k_do edit ingress"
alias ker="_k_do edit release"
alias kec="_k_do edit configmap"
alias kena="_k_do edit net-attach-def"
alias kenw="_k_do edit net"

## log
alias klp="_k_do logs pod"

alias kx="_k_do exec pod"
alias kfc="kubectl create -f"
alias kfd="kubectl delete -f"
alias kfp="kubectl patch -f"
alias kfa="kubectl apply -f"
alias kfr="_k_recreate_file"

## kubectl -n kube-system
alias ks="kubectl -n kube-system"
alias ksd="_k_scale deployment"
alias ksts="_k_scale sts"
fi
