#!/usr/bin/env bash
PROCESS=$0

test -z "$1" && exit 1
cd $(dirname $0)
source ./hguess
cd - >/dev/null

dst_ip=$PC_IP

do_route_init() {
    if ! ip route | grep -q "172.16.70.0/24 via $PC_IP";then
        ip route add 172.16.70.0/24 via $PC_IP
    fi
    hss pc 'iptables -I FORWARD -o virbr0 -s 192.168.10/23 -m comment --comment "pc-fwd-vm" -j ACCEPT'
}

ACTION=ssh

PASSWORD=
_execute() {
    if test -n "$PASSWORD";then
        set -x
        exec sshpass -p "$PASSWORD" "$@"
    else
        set -x
        exec "$@"
    fi
}


do_action() {
    local dst="$1"
    local res=$(do_guess $dst)
    if test -z "$res";then
        exit 1
    fi
    shift
    read dst_ip passwd <<<"$res"
    PASSWORD=$passwd
    if [ "$ACTION" = ssh ];then
        _execute ssh -oStrictHostKeyChecking=no $dst_ip "$@"
    elif [ "$ACTION" = upload ];then
        local src="$1"
        local dst="$2"

        test -n "$dst" || dst=/root/

        if test -f "$src";then
            _execute scp -oStrictHostKeyChecking=no $src "[$dst_ip]":"$dst"
        elif test -d "$src";then
            local src_parent=$(dirname $src)
            local src_filename=$(basename $src)

            tar czf - -C "$src_parent" "$src_filename" | _execute ssh -oStrictHostKeyChecking=no "$dst_ip" "cd $dst && tar zxf -"
        fi
    elif [ "$ACTION" = download ];then
        local src="$1"
        local dst="$2"

        local src_parent=$(dirname $src)
        local src_filename=$(basename $src)

        test -n "$dst" || dst=./


        if [[ "$src" == */ ]];then
            _execute ssh -oStrictHostKeyChecking=no "$dst_ip" tar czf - -C "$src_parent" "$src_filename"  \
                | { cd "$dst" && tar zxf - ; }
        else
            _execute scp -oStrictHostKeyChecking=no [$dst_ip]:$src "$dst"
        fi
    elif [ "$ACTION" = fxxk ];then
        update_ssh_known_hosts $dst_ip
        if pw=$(try_pws $dst_ip $passwd);then
            update_dict_file $dst $dst_ip $pw
            shift
            shift
            exec $PROCESS $dst "$@"
        fi
    fi
    exit

    if test -n "$JUMP_IP";then exec ssh -tt $JUMP_IP ssh $dst_ip "$@"
    fi
    if test -n "$passwd";then
        set -x
        exec sshpass -p $passwd ssh -oStrictHostKeyChecking=no $dst_ip "$@"
    else
        set -x
        exec ssh $dst_ip "$@"
    fi
}

if [ "$1"  = route ];then
    do_route_init
    exit
fi
if [ "$1" = u ];then
    ACTION=upload
    shift
elif [ "$1" = d ];then
    ACTION=download
    shift
elif [ "$2"  = fxxk ];then
    ACTION=fxxk
fi

do_action "$@"

