#!/bin/bash

_find_ns() {
    if test -n "$2";then
        kubectl get $1 --all-namespaces | awk -v p=$2 '{if ($2 == p) {print $1}}'
    fi
}

_k_describe() {
    local ns=$(_find_ns "$1" "$2")
    if test -n "$ns";then
        kubectl -n $ns describe $@
    else
        echo "can not find namespace for: $@"
        return
    fi
}

_k_edit() {
    local ns=$(_find_ns "$1" "$2")
    if test -n "$ns";then
        kubectl -n $ns edit $@
    else
        echo "can not find namespace for: $@"
        return
    fi
}

_k_logs() {
    local ns=$(_find_ns pod "$1")
    if test -n "$ns";then
        kubectl -n $ns logs "$@"
    else
        echo "can not find namespace for $1"
        return
    fi
}

_k_exec() {
    local ns=$(_find_ns pod "$1")
    if test -n "$ns";then
        local pod="$1"
        shift
        kubectl -n $ns exec "$pod" -- "$@"
    else
        echo "can not find namespace for $1"
        return
    fi
}

## get 
alias kgp='kubectl get pods --all-namespaces -o wide'
alias kgs='kubectl get svc --all-namespaces'
alias kgd='kubectl get deployment --all-namespaces'
alias kga='kubectl get all --all-namespaces'


## describe
alias kdp='_k_describe pod'
alias kds='_k_describe svc'
alias kdd='_k_describe deployment'

## edit
alias kep='_k_edit pod'
alias kes='_k_edit svc'
alias ked='_k_edit deployment'

## log
alias klp=_k_logs

## kubectl -n kube-system
alias ks='kubectl -n kube-system'


alias ke='_k_exec'

