#!/bin/bash

op=$1
file=$2

if [ "$op" != list ] && test -z "$2";then
    echo too few arguments
    exit 
fi


NS=

ns_run() {
    ip netns exec $NS "$@"
}

ns_exists() {
    ip netns | grep -q "^$NS\b"
}

ns_list_net() {
    printf "%s\t" $NS
    {
        ip netns exec $NS ip addr show eth0 | awk '{if ($1 == "inet" || $1 == "link/ether") {print $2}}'
        ip netns exec $NS ip route show default | awk '{print $3}'
    } | tr '\n' '\t'
    printf "\n"
}

if [ "$op" = start ];then
    mkdir -p /etc/vvm/vvm/
    file2=/etc/vvm/vvm/$file.conf
    if test -r $file2;then
        file=$file2
    fi
    source $file
    NS=vvm-$NAME

    if test -z "$NAME" || ns_exists;then
        echo $NS is invalid or alreadly exists
        exit 1
    fi
    ip netns add $NS
    ip link add veth-$NAME type veth peer name peer-$NAME
    ip link set peer-$NAME netns $NS

    ns_run ip link set peer-$NAME name eth0
    ns_run ip link set eth0 address $MAC
    ns_run ip addr add dev eth0 $IP
    ns_run ip link set eth0 up
    ns_run ip link set lo up
    test -z "$GW" || ns_run ip route add default via $GW
    ip link set veth-$NAME address $MAC
    ip link set veth-$NAME up


    port=veth-$NAME
    if test -n "$OVS_BR";then
        ovs-vsctl add-port $OVS_BR $port -- set interface $port external_ids:iface-id=$OVN_BR-$port
    fi
    if test -n "$OVN_BR";then
        ovn-nbctl lsp-add $OVN_BR $OVN_BR-$port -- lsp-set-addresses $OVN_BR-$port $MAC -- lsp-set-port-security $OVN_BR-$port $MAC
    fi

elif [ "$op" = stop ];then
    NAME=$file
    NS=vvm-$NAME
    if ! ns_exists;then
        echo $NAME does not exist
        exit 1
    fi
    ip link del veth-$NAME
    ip netns del $NS

    port=veth-$NAME
    iface_id=$(ovs-vsctl --if-exists get int $port external_ids:iface-id | tr -d '"')
    if [ "$iface_id" ];then
        ovn-nbctl --if-exists lsp-del $iface_id
    fi

    ovs-vsctl --if-exists del-port $port

elif [ "$op" = list ];then
    for ns in $(ip netns | sort |grep ^vvm- |awk '{print $1}')
    do
        NS=$ns
        ns_list_net
    done

elif [ "$op" = conn ];then
    NAME=$file
    NS=vvm-$NAME
    if ! ns_exists;then
        echo $NAME does not exist
        exit 1
    fi
    rcfile=/tmp/vvm-rc-$NAME
    cat > $rcfile <<EOF
source /root/.bashrc
export PS1="vvm@$NAME.\h:\w\$ "
rm -f $rcfile
EOF
    cd /root/
    exec ip netns exec $NS bash --rcfile $rcfile
elif [ "$op" = edit ];then
    mkdir -p /etc/vvm/vvm/
    file2=/etc/vvm/vvm/$file.conf
    if ! test -f $file2;then
        cat 1>$file2 <<EOF
NAME=vm1
MAC=0c:dd:00:00:00:00
IP=dhchp
IP=172.20.70.2/24
GW=172.20.70.1
OVS_BR=
OVN_BR=
ARG=
EOF
    fi
    vim $file2
    if ! test -s "$file2";then
        rm -f $file2
    fi
fi

